name: C++
on:
  workflow_call:
    inputs:
      cpp_std_version:
        required: true
        type: string
      build_type:
        required: false
        type: string
        default: "Debug"
      target:
        required: true
        type: string

jobs:
  # Linux
  linux-x64-gcc:
    name: Linux x64 (GCC)
    uses: cach30verfl0w/erebos/.github/workflows/linux-gcc.yml@main
    with:
      job_name: Linux x64 (GCC)
      image_name: ubuntu-22.04
      cpp_std_version: ${{inputs.cpp_std_version}}
      gcc_version: 12
      build_type: ${{inputs.build_type}}
      target: ${{inputs.target}}
  linux-x64-clang:
    name: Linux x64 (Clang)
    uses: cach30verfl0w/erebos/.github/workflows/linux-clang.yml@main
    with:
      job_name: Linux x64 (Clang)
      image_name: ubuntu-22.04
      cpp_std_version: ${{inputs.cpp_std_version}}
      clang_version: 15
      build_type: ${{inputs.build_type}}
      target: ${{inputs.target}}

  # macOS
  macos-x64-clang:
    name: macOS x86 (Clang)
    uses: cach30verfl0w/erebos/.github/workflows/macos-clang.yml@main
    with:
      job_name: macOS x64 (Clang)
      image_name: macos-13
      cpp_std_version: ${{inputs.cpp_std_version}}
      build_type: ${{inputs.build_type}}
      target: ${{inputs.target}}

  # Windows
  windows-x64-msvc:
    name: Windows x64 (MSVC)
    uses: cach30verfl0w/erebos/.github/workflows/windows-msvc.yml@main
    with:
      job_name: Windows x64 (MSVC)
      image_name: windows-2022
      cpp_std_version: ${{inputs.cpp_std_version}}
      build_type: ${{inputs.build_type}}
      target: ${{inputs.target}}
  windows-x64-clang:
    name: Windows x64 (Clang)
    uses: cach30verfl0w/erebos/.github/workflows/windows-clang.yml@main
    with:
      job_name: Windows x64 (Clang)
      image_name: windows-2022
      clang_version: 16
      cpp_std_version: ${{inputs.cpp_std_version}}
      build_type: ${{inputs.build_type}}
      target: ${{inputs.target}}