name: Build and Test
on:
  push:

jobs:
  editor-cpp-20-debug:
    name: Editor / C++ 20 (Debug)
    uses: cach30verfl0w/erebos/.github/workflows/cpp.yml@main
    with:
      cpp_std_version: 20
      target: erebos-editor
  tests-cpp-20-debug:
    name: Tests / C++ 20 (Debug)
    uses: cach30verfl0w/erebos/.github/workflows/cpp.yml@main
    with:
      cpp_std_version: 20
      target: erebos-tests